import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ScreenProvider } from "./context/ScreenSizeContext";
import { DragDropLayoutProvider } from "./context/DragDropLayoutContext";
import { EmailTemplateProvider } from "./context/EmailTemplateContext";
import { SelectedElementProvider } from "./context/SelectedElement";
import { HtmlContentProvider } from "./context/HtmlContentContext";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <ScreenProvider>
        <DragDropLayoutProvider>
          <EmailTemplateProvider>
            <SelectedElementProvider>
              <HtmlContentProvider>
                <html lang="en">
                  <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                  >
                    {children}
                  </body>
                </html>
              </HtmlContentProvider>
            </SelectedElementProvider>
          </EmailTemplateProvider>
        </DragDropLayoutProvider>
      </ScreenProvider>
    </ClerkProvider>
    
  );
}
